spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestUser
    username: postgres
    password: skillbox
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true
